### ISSUE TITLE
Remove `commas`?

### ISSUE THREAD

**Issue by delirious-lettuce** [progrmoiz/python-snippets#4]
https://github.com/progrmoiz/python-snippets/blob/8d24dd5874d9e931f205b4ea700c974f60112307/formats.py#L11

```python
In[12]: for test in (-1, 1.23, 12, 123, 1234, 1234567):
   ...:     print(f'{test:,}')
   ...: 
-1
1.23
12
123
1,234
1,234,567

```

**Comment by progrmoiz** [comment]
https://github.com/progrmoiz/python-snippets/blob/875990bdddba8d2f3c526c89c98ed781a8273512/formats.py#L25

Added commas1
